fix issue #18 refresh on save
transkript/reportcard-frontend pull request #21
Opened 2022-06-18 08:50 UTC by mulfranck

A little shift of functions seems to do the trick
 - The Modal close when the save button is clicked.
 - The list updated

2022-06-18 12:46 UTC, elroykanye requested changes
Amazing! Some few comments below

2022-06-18 12:46 UTC, elroykanye commented on src/app/modules/reusable/student/save-student/save-student.component.ts
> +    this.closeModal();
I personally think that this is not in the scope of this issue and should then not be included in your PR. Let's focus on ensuring that only what is necessary for a specific issue should be taken care of. Thanks ☺️

2022-06-20 08:48 UTC, mulfranck commented on src/app/modules/reusable/student/save-student/save-student.component.ts
> +    this.closeModal();
I am a bit confused as my understanding the `save-student` container controls the Modal for adding students, closing the modal is also controlled by the `save-student` components right? So to close the modal on __save__ the `closeModal` method should be called in the `saveStudent` method.

2022-06-20 09:10 UTC, mulfranck commented on src/app/modules/reusable/student/save-student/save-student.component.ts
> +    this.closeModal();
The _save-student_ container controls the Modal for adding students, closing the modal is also controlled by the _save-student_ components right? So to close the modal on __save__ the `closeModal` method should be called in the `saveStudent` method, so methought.

I must be misunderstanding something, do you have a suggestion as per this issue?

2022-06-21 11:25 UTC, mulfranck commented on src/app/modules/reusable/student/save-student/save-student.component.ts
> +    this.closeModal();
Okay, I get it now. Thanks.

2022-06-23 08:53 UTC, closed without merging

2022-06-23 15:00 UTC, elroykanye commented
I still think this could solve the issue except for the part where I stated is not necessary.